import { ReactNode } from "react"
import "@/styles/globals.css"
import { Noto_Sans_JP } from "next/font/google"
import { OutSideContainer } from "@/components/layouts/OutSideContainer"
import { MainContainer } from "@/components/layouts/MainContainer"
import { SideBar } from "@/components/layouts/SideBar"
import { Header } from "@/components/layouts/Header"
import { Profile } from "@/components/elements/Profile"
import { Main } from "@/components/layouts/Main"

const inter = Noto_Sans_JP({ subsets: ["latin"] })

// TODO: 最適化する
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="ja">
    <body className={inter.className}>
      <OutSideContainer>
        {/* TODO: 広告なり付ける */}
        <SideBar />
        <MainContainer>
          <Header />
          <Main>{children}</Main>
        </MainContainer>
        <SideBar>
          <div className="mt-[100px] flex justify-center">
            <Profile />
          </div>
        </SideBar>
      </OutSideContainer>
    </body>
  </html>
)

export default RootLayout
