name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update_content]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-optional

      - name: Build
        env:
          NEWT_API_TOKEN: ${{ secrets.NEWT_API_TOKEN }}
          SPACE_UID: ${{ secrets.SPACE_UID }}
          APP_UID: ${{ secrets.APP_UID }}
          NEXT_PUBLIC_GA_TAG_ID: ${{ vars.NEXT_PUBLIC_GA_TAG_ID }}
        run: yarn build

      - name: Add CNAME
        run: cp ./CNAME ./out/

      - name: Upload to artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

  deploy:
    needs: build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
